version: "3.7"

services:
  scrapper:
    build: ./scrapper/
    networks:
      - default
    environment:
      BACKEND_GRPC_HOST: backend

  scrapper_mvg_avg:
    build: ./scrapper/
    networks:
      - default
    environment:
      BACKEND_GRPC_HOST: backend
    command: ["app.avg_handler"]

  scrapper_storage_mvg_avg:
    build: ./scrapper/
    networks:
      - default
    environment:
      BACKEND_GRPC_HOST: backend
    command: ["app.storage_handler"]

  lambda:
    image: nginx
    restart: on-failure
    networks:
      - default
    ports:
      - 8080:8080
    volumes:
      - ./lambda.nginx.conf:/etc/nginx/conf.d/lambda.nginx.conf:ro

  stepfunctions:
    image: amazon/aws-stepfunctions-local
    networks:
      - default
    environment:
      LAMBDA_ENDPOINT: http://lambda:8080


  scrapper_sfn_create:
    image: amazon/aws-cli
    restart: on-failure
    networks:
      - default
    volumes:
      - ./scrapper/sfn.json:/code/sfn.json
    environment:
      AWS_ACCESS_KEY_ID: fake
      AWS_SECRET_ACCESS_KEY: fake
      AWS_DEFAULT_REGION: local
    command: |
      stepfunctions
        --endpoint-url http://stepfunctions:8083
        create-state-machine --definition file:///code/sfn.json
        --name "scrapper"
        --role-arn "arn:aws:iam::012345678901:role/DummyRole"

  scrapper_sfn_invoke:
    image: amazon/aws-cli
    restart: on-failure
    networks:
      - default
    environment:
      AWS_ACCESS_KEY_ID: fake
      AWS_SECRET_ACCESS_KEY: fake
      AWS_DEFAULT_REGION: local
    command: |
      stepfunctions
        --endpoint-url http://stepfunctions:8083 start-execution
        --state-machine-arn "arn:aws:states:us-east-1:123456789012:stateMachine:scrapper"
