version: "3.7"

services:
  db:
    image: postgres:latest
    restart: always
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s 

  migrate:
    image: migrate/migrate:v4.16.2
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
    environment:
      POSTGRES_URI: 
    volumes:
      - ./migrate/:/migrations:Z
    command: -database postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable -path /migrations/ up

  backend:
    build: ./backend/
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
    environment:
      POSTGRES_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
    entrypoint: [ "python", "/code/service.py" ]

  test_backend:
    build: ./backend/
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started
    networks:
      - default
    entrypoint: [ "pytest", "/code/" ]
    environment:
      BACKEND_GRPC_HOST: backend

  compute:
    build: ./compute/
    restart: always
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started
    networks:
      - default
    environment:
      BACKEND_GRPC_HOST: backend
    entrypoint: [ "python", "/code/service.py" ]


  api:
    build: ./api/
    restart: always
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started
    networks:
      - default
    environment:
      BACKEND_GRPC_HOST: backend
    entrypoint: [ "uvicorn", "--host", "api", "service:app", "--reload" ]

  scrapper:
    build: ./scrapper/
    networks:
      - default
    environment:
      BACKEND_GRPC_HOST: backend

  stepfunctions:
    image: amazon/aws-stepfunctions-local
    networks:
      - default
    environment:
      LAMBDA_ENDPOINT: http://scrapper:8080


  scrapper_sfn_create:
    image: amazon/aws-cli
    restart: on-failure
    networks:
      - default
    volumes:
      - ./scrapper/sfn.json:/code/sfn.json
    environment:
      AWS_ACCESS_KEY_ID: fake
      AWS_SECRET_ACCESS_KEY: fake
      AWS_DEFAULT_REGION: local
    command: |
      stepfunctions
        --endpoint-url http://stepfunctions:8083
        create-state-machine --definition file:///code/sfn.json
        --name "scrapper"
        --role-arn "arn:aws:iam::012345678901:role/DummyRole"

  scrapper_sfn_invoke:
    image: amazon/aws-cli
    restart: on-failure
    networks:
      - default
    environment:
      AWS_ACCESS_KEY_ID: fake
      AWS_SECRET_ACCESS_KEY: fake
      AWS_DEFAULT_REGION: local
    command: |
      stepfunctions
        --endpoint-url http://stepfunctions:8083 start-execution
        --state-machine-arn "arn:aws:states:us-east-1:123456789012:stateMachine:scrapper"
