version: "3.7"

services:
  db:
    image: postgres:latest
    restart: always
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  migrate:
    image: migrate/migrate:v4.16.2
    restart: on-failure
    networks:
      - default
    environment:
      POSTGRES_URI: 
    volumes:
      - ./migrate/:/migrations:Z
    command: -database postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable -path /migrations/ up

  backend:
    build: ./backend/
    restart: always
    networks:
      - default
    environment:
      POSTGRES_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
    entrypoint: [ "python", "/code/service.py" ]

  test_backend:
    build: ./backend/
    networks:
      - default
    entrypoint: [ "pytest", "/code/" ]
    environment:
      BACKEND_GRPC_HOST: backend

