version: "3.7"

services:
  db:
    image: postgres:latest
    restart: always
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s 

  migrate:
    image: migrate/migrate:v4.16.2
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
    environment:
      POSTGRES_URI: 
    volumes:
      - ./migrate/:/migrations:Z
    command: -database postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable -path /migrations/ up

  backend:
    build: ./backend/
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
    environment:
      POSTGRES_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
    entrypoint: [ "python", "/code/service.py" ]

  cpp_backend:
    build: ./cpp_backend/

  test_backend:
    build: ./backend/
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started
    networks:
      - default
    entrypoint: [ "pytest", "/code/" ]
    environment:
      BACKEND_GRPC_HOST: backend

  compute:
    build: ./compute/
    restart: always
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started
    networks:
      - default
    environment:
      BACKEND_GRPC_HOST: backend
    entrypoint: [ "python", "/code/service.py" ]


  api:
    build: ./api/
    restart: always
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started
    networks:
      - default
    environment:
      BACKEND_GRPC_HOST: backend
    ports:
      - 8000:8000
    entrypoint: [ "uvicorn", "--host", "api", "service:app", "--reload" ]

  test_api:
    build: ./api/
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started
    networks:
      - default
    entrypoint: [ "pytest", "/code/" ]
    environment:
      BACKEND_GRPC_HOST: backend
