# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import backend_pb2 as backend__pb2


class PricingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SavePrice = channel.unary_unary(
                '/Pricing/SavePrice',
                request_serializer=backend__pb2.Stock.SerializeToString,
                response_deserializer=backend__pb2.Stock.FromString,
                )


class PricingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SavePrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PricingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SavePrice': grpc.unary_unary_rpc_method_handler(
                    servicer.SavePrice,
                    request_deserializer=backend__pb2.Stock.FromString,
                    response_serializer=backend__pb2.Stock.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Pricing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Pricing(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SavePrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Pricing/SavePrice',
            backend__pb2.Stock.SerializeToString,
            backend__pb2.Stock.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
